package uaic.fii.MarvelMonPlay.models;

public enum Event {
    START_FIGHT, LOST_FIGHT, WON_FIGHT, CONTINUE_FIGHT, END_LEVEL, LOST_GAME, CHOOSE_WATER,CHOOSE_AIR,CHOOSE_EARTH,CHOOSE_FIRE, WON_GAME, NONE
}
