package uaic.fii.MarvelMonPlay.models;

public enum Event {
    START_FIGHT, LOST_FIGHT, WON_FIGHT, CONTINUE_FIGHT, END_LEVEL, LOST_GAME, CHOOSE_WATER, CHOOSE_AIR, CHOOSE_EARTH,
    CHOOSE_FIRE, WON_GAME, NONE, PICK_POKEMON_TO_FIGHT, INCREASE_POWER_ATTACK,
    INCREASE_DEFENSE,
    DECREASE_ENEMY_POWER_ATTACK,
    DECREASE_ENEMY_DEFENSE,
    COLLECT_WATER_ITEM,COLLECT_FIRE_ITEM,COLLECT_AIR_ITEM,COLLECT_EARTH_ITEM
}
